name: continous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: install dependecies
        run: cd web && npm install

      - name: run tests
        run: cd web && npm test

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: install dependecies
        run: cd web && npm install

      - name: run linter
        run: npm run lint


